### ISSUE TITLE
segfault in libvlc

### ISSUE THREAD

**Issue by mbkma** [FreaxMATE/Ojo#1]
Hi there,

that is an enjoyable application so far indeed. A minor issue is, that on Debian buster I get a segfault.
```
(gdb) run player 

Thread 1 "player" received signal SIGSEGV, Segmentation fault.
0x00007ffff72ad06c in libvlc_media_player_new ()
   from /lib/x86_64-linux-gnu/libvlc.so.5
(gdb) backtrace
#0  0x00007ffff72ad06c in libvlc_media_player_new ()
    at /lib/x86_64-linux-gnu/libvlc.so.5
#1  0x0000555555556d14 in initVlc ()
#2  0x000055555555655e in main ()
```

That happens to the plain vlc gtk demo as well, so it might be an issue within the library.
libvlc-dev version: 3.0.7-1
I'll try to fix it, but help would be appreciated :)

**Comment by mbkma** [comment]
closed, as this is not an Ojo issue
It seems to affect my current setup only
EDIT: I had to install vlc, not only libvlc-dev, now it works just fine
